### ISSUE TITLE
你的两个文件夹的代码怎么是一样的吗？还有就是我怎么找不到你实现Tucker分解的部分呢？

### ISSUE THREAD

**Issue by zhenchengchang** [MyTHWN/MTER#3]

**Comment by MyTHWN** [comment]
One is implemented with standard CP decomposition, and the other is tucker decomposition. I did not explicitly define the tucker decomposition method in my code. Sorry for the poor organization and inconvenience. But the tucker decomposition could be simply implemented by some packages like the numpy.einsum, which is exactly what I used. Later I will release a new implementation that makes everything clear. Thank you!
